// Code generated by goctl. DO NOT EDIT.
package optionsclient

import (
	"context"

	"github.com/reyfi/reyfi-backend/app/options/rpc/options"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetChainsReq        = options.GetChainsReq
	GetChainsResp       = options.GetChainsResp
	OptionChain         = options.OptionChain
	OptionStrike        = options.OptionStrike
	GetVolSurfaceReq    = options.GetVolSurfaceReq
	GetVolSurfaceResp   = options.GetVolSurfaceResp
	VolPoint            = options.VolPoint
	GetPositionsReq     = options.GetPositionsReq
	GetPositionsResp    = options.GetPositionsResp
	OptionsPositionInfo = options.OptionsPositionInfo
	BuildWriteOptionReq = options.BuildWriteOptionReq
	BuildBuyOptionReq   = options.BuildBuyOptionReq
	BuildExerciseReq    = options.BuildExerciseReq
	BuildTxResp         = options.BuildTxResp
)

type OptionsService interface {
	GetChains(ctx context.Context, in *GetChainsReq, opts ...grpc.CallOption) (*GetChainsResp, error)
	GetVolSurface(ctx context.Context, in *GetVolSurfaceReq, opts ...grpc.CallOption) (*GetVolSurfaceResp, error)
	GetPositions(ctx context.Context, in *GetPositionsReq, opts ...grpc.CallOption) (*GetPositionsResp, error)
	BuildWriteOption(ctx context.Context, in *BuildWriteOptionReq, opts ...grpc.CallOption) (*BuildTxResp, error)
	BuildBuyOption(ctx context.Context, in *BuildBuyOptionReq, opts ...grpc.CallOption) (*BuildTxResp, error)
	BuildExercise(ctx context.Context, in *BuildExerciseReq, opts ...grpc.CallOption) (*BuildTxResp, error)
}

type defaultOptionsService struct {
	cli zrpc.Client
}

func NewOptionsService(cli zrpc.Client) OptionsService {
	return &defaultOptionsService{cli: cli}
}

func (d *defaultOptionsService) GetChains(ctx context.Context, in *GetChainsReq, opts ...grpc.CallOption) (*GetChainsResp, error) {
	client := options.NewOptionsServiceClient(d.cli.Conn())
	return client.GetChains(ctx, in, opts...)
}

func (d *defaultOptionsService) GetVolSurface(ctx context.Context, in *GetVolSurfaceReq, opts ...grpc.CallOption) (*GetVolSurfaceResp, error) {
	client := options.NewOptionsServiceClient(d.cli.Conn())
	return client.GetVolSurface(ctx, in, opts...)
}

func (d *defaultOptionsService) GetPositions(ctx context.Context, in *GetPositionsReq, opts ...grpc.CallOption) (*GetPositionsResp, error) {
	client := options.NewOptionsServiceClient(d.cli.Conn())
	return client.GetPositions(ctx, in, opts...)
}

func (d *defaultOptionsService) BuildWriteOption(ctx context.Context, in *BuildWriteOptionReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := options.NewOptionsServiceClient(d.cli.Conn())
	return client.BuildWriteOption(ctx, in, opts...)
}

func (d *defaultOptionsService) BuildBuyOption(ctx context.Context, in *BuildBuyOptionReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := options.NewOptionsServiceClient(d.cli.Conn())
	return client.BuildBuyOption(ctx, in, opts...)
}

func (d *defaultOptionsService) BuildExercise(ctx context.Context, in *BuildExerciseReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := options.NewOptionsServiceClient(d.cli.Conn())
	return client.BuildExercise(ctx, in, opts...)
}
