// Code generated by goctl. DO NOT EDIT.
package lendingclient

import (
	"context"

	"github.com/reyfi/reyfi-backend/app/lending/rpc/lending"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMarketsReq        = lending.GetMarketsReq
	GetMarketsResp       = lending.GetMarketsResp
	MarketInfo           = lending.MarketInfo
	GetMarketDetailReq   = lending.GetMarketDetailReq
	GetMarketDetailResp  = lending.GetMarketDetailResp
	GetUserPositionReq   = lending.GetUserPositionReq
	GetUserPositionResp  = lending.GetUserPositionResp
	UserLendingPosition  = lending.UserLendingPosition
	GetLiquidationsReq   = lending.GetLiquidationsReq
	GetLiquidationsResp  = lending.GetLiquidationsResp
	LiquidationInfo      = lending.LiquidationInfo
	BuildSupplyReq       = lending.BuildSupplyReq
	BuildBorrowReq       = lending.BuildBorrowReq
	BuildRepayReq        = lending.BuildRepayReq
	BuildWithdrawReq     = lending.BuildWithdrawReq
	BuildTxResp          = lending.BuildTxResp
	RateHistoryItem      = lending.RateHistoryItem
)

type LendingService interface {
	GetMarkets(ctx context.Context, in *GetMarketsReq, opts ...grpc.CallOption) (*GetMarketsResp, error)
	GetMarketDetail(ctx context.Context, in *GetMarketDetailReq, opts ...grpc.CallOption) (*GetMarketDetailResp, error)
	GetUserPosition(ctx context.Context, in *GetUserPositionReq, opts ...grpc.CallOption) (*GetUserPositionResp, error)
	GetLiquidations(ctx context.Context, in *GetLiquidationsReq, opts ...grpc.CallOption) (*GetLiquidationsResp, error)
	BuildSupply(ctx context.Context, in *BuildSupplyReq, opts ...grpc.CallOption) (*BuildTxResp, error)
	BuildBorrow(ctx context.Context, in *BuildBorrowReq, opts ...grpc.CallOption) (*BuildTxResp, error)
	BuildRepay(ctx context.Context, in *BuildRepayReq, opts ...grpc.CallOption) (*BuildTxResp, error)
	BuildWithdraw(ctx context.Context, in *BuildWithdrawReq, opts ...grpc.CallOption) (*BuildTxResp, error)
}

type defaultLendingService struct {
	cli zrpc.Client
}

func NewLendingService(cli zrpc.Client) LendingService {
	return &defaultLendingService{cli: cli}
}

func (d *defaultLendingService) GetMarkets(ctx context.Context, in *GetMarketsReq, opts ...grpc.CallOption) (*GetMarketsResp, error) {
	client := lending.NewLendingServiceClient(d.cli.Conn())
	return client.GetMarkets(ctx, in, opts...)
}

func (d *defaultLendingService) GetMarketDetail(ctx context.Context, in *GetMarketDetailReq, opts ...grpc.CallOption) (*GetMarketDetailResp, error) {
	client := lending.NewLendingServiceClient(d.cli.Conn())
	return client.GetMarketDetail(ctx, in, opts...)
}

func (d *defaultLendingService) GetUserPosition(ctx context.Context, in *GetUserPositionReq, opts ...grpc.CallOption) (*GetUserPositionResp, error) {
	client := lending.NewLendingServiceClient(d.cli.Conn())
	return client.GetUserPosition(ctx, in, opts...)
}

func (d *defaultLendingService) GetLiquidations(ctx context.Context, in *GetLiquidationsReq, opts ...grpc.CallOption) (*GetLiquidationsResp, error) {
	client := lending.NewLendingServiceClient(d.cli.Conn())
	return client.GetLiquidations(ctx, in, opts...)
}

func (d *defaultLendingService) BuildSupply(ctx context.Context, in *BuildSupplyReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := lending.NewLendingServiceClient(d.cli.Conn())
	return client.BuildSupply(ctx, in, opts...)
}

func (d *defaultLendingService) BuildBorrow(ctx context.Context, in *BuildBorrowReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := lending.NewLendingServiceClient(d.cli.Conn())
	return client.BuildBorrow(ctx, in, opts...)
}

func (d *defaultLendingService) BuildRepay(ctx context.Context, in *BuildRepayReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := lending.NewLendingServiceClient(d.cli.Conn())
	return client.BuildRepay(ctx, in, opts...)
}

func (d *defaultLendingService) BuildWithdraw(ctx context.Context, in *BuildWithdrawReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := lending.NewLendingServiceClient(d.cli.Conn())
	return client.BuildWithdraw(ctx, in, opts...)
}
