// Code generated by goctl. DO NOT EDIT.
// goctl rpc protoc — go-zero style client wrapper for DexService.
package dexclient

import (
	"context"

	"github.com/reyfi/reyfi-backend/app/dex/rpc/dex"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetPairsReq       = dex.GetPairsReq
	GetPairsResp      = dex.GetPairsResp
	PairInfo          = dex.PairInfo
	GetPairDetailReq  = dex.GetPairDetailReq
	GetPairDetailResp = dex.GetPairDetailResp
	GetTradesReq      = dex.GetTradesReq
	GetTradesResp     = dex.GetTradesResp
	TradeInfo         = dex.TradeInfo
	GetCandlesReq     = dex.GetCandlesReq
	GetCandlesResp    = dex.GetCandlesResp
	CandleInfo        = dex.CandleInfo
	GetOverviewReq    = dex.GetOverviewReq
	GetOverviewResp   = dex.GetOverviewResp
	GetPositionsReq   = dex.GetPositionsReq
	GetPositionsResp  = dex.GetPositionsResp
	LPPosition        = dex.LPPosition
	BuildSwapReq      = dex.BuildSwapReq
	BuildSwapResp     = dex.BuildSwapResp
	FindBestRouteReq  = dex.FindBestRouteReq
	FindBestRouteResp = dex.FindBestRouteResp
	RouteInfo         = dex.RouteInfo
)

// DexService is the client API for DexService service.
type DexService interface {
	GetPairs(ctx context.Context, in *GetPairsReq, opts ...grpc.CallOption) (*GetPairsResp, error)
	GetPairDetail(ctx context.Context, in *GetPairDetailReq, opts ...grpc.CallOption) (*GetPairDetailResp, error)
	GetTrades(ctx context.Context, in *GetTradesReq, opts ...grpc.CallOption) (*GetTradesResp, error)
	GetCandles(ctx context.Context, in *GetCandlesReq, opts ...grpc.CallOption) (*GetCandlesResp, error)
	GetOverview(ctx context.Context, in *GetOverviewReq, opts ...grpc.CallOption) (*GetOverviewResp, error)
	GetPositions(ctx context.Context, in *GetPositionsReq, opts ...grpc.CallOption) (*GetPositionsResp, error)
	BuildSwap(ctx context.Context, in *BuildSwapReq, opts ...grpc.CallOption) (*BuildSwapResp, error)
	FindBestRoute(ctx context.Context, in *FindBestRouteReq, opts ...grpc.CallOption) (*FindBestRouteResp, error)
}

type defaultDexService struct {
	cli zrpc.Client
}

func NewDexService(cli zrpc.Client) DexService {
	return &defaultDexService{cli: cli}
}

func (d *defaultDexService) GetPairs(ctx context.Context, in *GetPairsReq, opts ...grpc.CallOption) (*GetPairsResp, error) {
	client := dex.NewDexServiceClient(d.cli.Conn())
	return client.GetPairs(ctx, in, opts...)
}

func (d *defaultDexService) GetPairDetail(ctx context.Context, in *GetPairDetailReq, opts ...grpc.CallOption) (*GetPairDetailResp, error) {
	client := dex.NewDexServiceClient(d.cli.Conn())
	return client.GetPairDetail(ctx, in, opts...)
}

func (d *defaultDexService) GetTrades(ctx context.Context, in *GetTradesReq, opts ...grpc.CallOption) (*GetTradesResp, error) {
	client := dex.NewDexServiceClient(d.cli.Conn())
	return client.GetTrades(ctx, in, opts...)
}

func (d *defaultDexService) GetCandles(ctx context.Context, in *GetCandlesReq, opts ...grpc.CallOption) (*GetCandlesResp, error) {
	client := dex.NewDexServiceClient(d.cli.Conn())
	return client.GetCandles(ctx, in, opts...)
}

func (d *defaultDexService) GetOverview(ctx context.Context, in *GetOverviewReq, opts ...grpc.CallOption) (*GetOverviewResp, error) {
	client := dex.NewDexServiceClient(d.cli.Conn())
	return client.GetOverview(ctx, in, opts...)
}

func (d *defaultDexService) GetPositions(ctx context.Context, in *GetPositionsReq, opts ...grpc.CallOption) (*GetPositionsResp, error) {
	client := dex.NewDexServiceClient(d.cli.Conn())
	return client.GetPositions(ctx, in, opts...)
}

func (d *defaultDexService) BuildSwap(ctx context.Context, in *BuildSwapReq, opts ...grpc.CallOption) (*BuildSwapResp, error) {
	client := dex.NewDexServiceClient(d.cli.Conn())
	return client.BuildSwap(ctx, in, opts...)
}

func (d *defaultDexService) FindBestRoute(ctx context.Context, in *FindBestRouteReq, opts ...grpc.CallOption) (*FindBestRouteResp, error) {
	client := dex.NewDexServiceClient(d.cli.Conn())
	return client.FindBestRoute(ctx, in, opts...)
}
