// Code generated by goctl. DO NOT EDIT.
package bondsclient

import (
	"context"

	"github.com/reyfi/reyfi-backend/app/bonds/rpc/bonds"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMarketsReq       = bonds.GetMarketsReq
	GetMarketsResp      = bonds.GetMarketsResp
	BondMarketInfo      = bonds.BondMarketInfo
	GetMarketDetailReq  = bonds.GetMarketDetailReq
	GetMarketDetailResp = bonds.GetMarketDetailResp
	GetPositionsReq     = bonds.GetPositionsReq
	GetPositionsResp    = bonds.GetPositionsResp
	BondPositionInfo    = bonds.BondPositionInfo
	BuildPurchaseReq    = bonds.BuildPurchaseReq
	BuildClaimReq       = bonds.BuildClaimReq
	BuildTxResp         = bonds.BuildTxResp
)

type BondsService interface {
	GetMarkets(ctx context.Context, in *GetMarketsReq, opts ...grpc.CallOption) (*GetMarketsResp, error)
	GetMarketDetail(ctx context.Context, in *GetMarketDetailReq, opts ...grpc.CallOption) (*GetMarketDetailResp, error)
	GetPositions(ctx context.Context, in *GetPositionsReq, opts ...grpc.CallOption) (*GetPositionsResp, error)
	BuildPurchase(ctx context.Context, in *BuildPurchaseReq, opts ...grpc.CallOption) (*BuildTxResp, error)
	BuildClaim(ctx context.Context, in *BuildClaimReq, opts ...grpc.CallOption) (*BuildTxResp, error)
}

type defaultBondsService struct {
	cli zrpc.Client
}

func NewBondsService(cli zrpc.Client) BondsService {
	return &defaultBondsService{cli: cli}
}

func (d *defaultBondsService) GetMarkets(ctx context.Context, in *GetMarketsReq, opts ...grpc.CallOption) (*GetMarketsResp, error) {
	client := bonds.NewBondsServiceClient(d.cli.Conn())
	return client.GetMarkets(ctx, in, opts...)
}

func (d *defaultBondsService) GetMarketDetail(ctx context.Context, in *GetMarketDetailReq, opts ...grpc.CallOption) (*GetMarketDetailResp, error) {
	client := bonds.NewBondsServiceClient(d.cli.Conn())
	return client.GetMarketDetail(ctx, in, opts...)
}

func (d *defaultBondsService) GetPositions(ctx context.Context, in *GetPositionsReq, opts ...grpc.CallOption) (*GetPositionsResp, error) {
	client := bonds.NewBondsServiceClient(d.cli.Conn())
	return client.GetPositions(ctx, in, opts...)
}

func (d *defaultBondsService) BuildPurchase(ctx context.Context, in *BuildPurchaseReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := bonds.NewBondsServiceClient(d.cli.Conn())
	return client.BuildPurchase(ctx, in, opts...)
}

func (d *defaultBondsService) BuildClaim(ctx context.Context, in *BuildClaimReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := bonds.NewBondsServiceClient(d.cli.Conn())
	return client.BuildClaim(ctx, in, opts...)
}
