// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/reyfi/reyfi-backend/app/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/bonds/markets",
				Handler: BondsGetMarketsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bonds/markets/:marketAddress",
				Handler: BondsGetMarketDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dex/overview",
				Handler: DexGetOverviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dex/pairs",
				Handler: DexGetPairsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dex/pairs/:pairAddress",
				Handler: DexGetPairDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dex/pairs/:pairAddress/candles",
				Handler: DexGetCandlesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dex/pairs/:pairAddress/trades",
				Handler: DexGetTradesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dex/route",
				Handler: DexFindRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/futures/markets",
				Handler: FuturesGetMarketsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/futures/markets/:marketAddress",
				Handler: FuturesGetMarketDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/futures/markets/:marketAddress/funding",
				Handler: FuturesGetFundingHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/governance/proposals",
				Handler: GovGetProposalsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/governance/proposals/:proposalId",
				Handler: GovGetProposalDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/governance/proposals/:proposalId/votes",
				Handler: GovGetVotesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/lending/liquidations",
				Handler: LendingGetLiquidationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/lending/markets",
				Handler: LendingGetMarketsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/lending/markets/:assetAddress",
				Handler: LendingGetMarketDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/options/chains",
				Handler: OptionsGetChainsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/options/vol-surface/:underlying",
				Handler: OptionsGetVolSurfaceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/sync-status",
				Handler: SystemSyncStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/auth/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/auth/nonce",
				Handler: UserGetNonceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/auth/refresh",
				Handler: UserRefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vault/:vaultAddress",
				Handler: VaultGetDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vault/list",
				Handler: VaultGetListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/bonds/claim/build",
				Handler: BondsBuildClaimHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bonds/positions",
				Handler: BondsGetPositionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bonds/purchase/build",
				Handler: BondsBuildPurchaseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dex/positions",
				Handler: DexGetPositionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dex/swap/build",
				Handler: DexBuildSwapHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/futures/position/adjust-margin",
				Handler: FuturesBuildAdjustMarginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/futures/position/close",
				Handler: FuturesBuildCloseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/futures/position/open",
				Handler: FuturesBuildOpenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/futures/positions",
				Handler: FuturesGetPositionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/governance/lock/build",
				Handler: GovBuildLockHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/governance/ve-lock",
				Handler: GovGetVeLockHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/governance/vote/build",
				Handler: GovBuildVoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/lending/borrow/build",
				Handler: LendingBuildBorrowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/lending/position",
				Handler: LendingGetUserPositionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/lending/repay/build",
				Handler: LendingBuildRepayHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/lending/supply/build",
				Handler: LendingBuildSupplyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/lending/withdraw/build",
				Handler: LendingBuildWithdrawHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/options/positions",
				Handler: OptionsGetPositionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/activity",
				Handler: UserGetActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/portfolio",
				Handler: UserGetPortfolioHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/settings",
				Handler: UserUpdateSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vault/deposit/build",
				Handler: VaultBuildDepositHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vault/positions",
				Handler: VaultGetPositionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vault/withdraw/build",
				Handler: VaultBuildWithdrawHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
