// Code generated by goctl. DO NOT EDIT.
package userclient

import (
	"context"

	"github.com/reyfi/reyfi-backend/app/user/rpc/user"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetNonceReq      = user.GetNonceReq
	GetNonceResp     = user.GetNonceResp
	LoginReq         = user.LoginReq
	LoginResp        = user.LoginResp
	RefreshTokenReq  = user.RefreshTokenReq
	RefreshTokenResp = user.RefreshTokenResp
	GetPortfolioReq  = user.GetPortfolioReq
	GetPortfolioResp = user.GetPortfolioResp
	GetActivityReq   = user.GetActivityReq
	GetActivityResp  = user.GetActivityResp
	UpdateSettingsReq  = user.UpdateSettingsReq
	UpdateSettingsResp = user.UpdateSettingsResp
	ModuleAllocation = user.ModuleAllocation
	RiskSummary      = user.RiskSummary
	ActivityItem     = user.ActivityItem
)

type UserService interface {
	GetNonce(ctx context.Context, in *GetNonceReq, opts ...grpc.CallOption) (*GetNonceResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
	GetPortfolio(ctx context.Context, in *GetPortfolioReq, opts ...grpc.CallOption) (*GetPortfolioResp, error)
	GetActivity(ctx context.Context, in *GetActivityReq, opts ...grpc.CallOption) (*GetActivityResp, error)
	UpdateSettings(ctx context.Context, in *UpdateSettingsReq, opts ...grpc.CallOption) (*UpdateSettingsResp, error)
}

type defaultUserService struct {
	cli zrpc.Client
}

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{cli: cli}
}

func (d *defaultUserService) GetNonce(ctx context.Context, in *GetNonceReq, opts ...grpc.CallOption) (*GetNonceResp, error) {
	client := user.NewUserServiceClient(d.cli.Conn())
	return client.GetNonce(ctx, in, opts...)
}

func (d *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserServiceClient(d.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (d *defaultUserService) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := user.NewUserServiceClient(d.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (d *defaultUserService) GetPortfolio(ctx context.Context, in *GetPortfolioReq, opts ...grpc.CallOption) (*GetPortfolioResp, error) {
	client := user.NewUserServiceClient(d.cli.Conn())
	return client.GetPortfolio(ctx, in, opts...)
}

func (d *defaultUserService) GetActivity(ctx context.Context, in *GetActivityReq, opts ...grpc.CallOption) (*GetActivityResp, error) {
	client := user.NewUserServiceClient(d.cli.Conn())
	return client.GetActivity(ctx, in, opts...)
}

func (d *defaultUserService) UpdateSettings(ctx context.Context, in *UpdateSettingsReq, opts ...grpc.CallOption) (*UpdateSettingsResp, error) {
	client := user.NewUserServiceClient(d.cli.Conn())
	return client.UpdateSettings(ctx, in, opts...)
}
