// Code generated by goctl. DO NOT EDIT.
package governanceclient

import (
	"context"

	"github.com/reyfi/reyfi-backend/app/governance/rpc/governance"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetProposalsReq       = governance.GetProposalsReq
	GetProposalsResp      = governance.GetProposalsResp
	ProposalInfo          = governance.ProposalInfo
	GetProposalDetailReq  = governance.GetProposalDetailReq
	GetProposalDetailResp = governance.GetProposalDetailResp
	GetVotesReq           = governance.GetVotesReq
	GetVotesResp          = governance.GetVotesResp
	VoteInfo              = governance.VoteInfo
	GetVeLockReq          = governance.GetVeLockReq
	GetVeLockResp         = governance.GetVeLockResp
	BuildVoteReq          = governance.BuildVoteReq
	BuildLockReq          = governance.BuildLockReq
	BuildTxResp           = governance.BuildTxResp
)

type GovernanceService interface {
	GetProposals(ctx context.Context, in *GetProposalsReq, opts ...grpc.CallOption) (*GetProposalsResp, error)
	GetProposalDetail(ctx context.Context, in *GetProposalDetailReq, opts ...grpc.CallOption) (*GetProposalDetailResp, error)
	GetVotes(ctx context.Context, in *GetVotesReq, opts ...grpc.CallOption) (*GetVotesResp, error)
	GetVeLock(ctx context.Context, in *GetVeLockReq, opts ...grpc.CallOption) (*GetVeLockResp, error)
	BuildVote(ctx context.Context, in *BuildVoteReq, opts ...grpc.CallOption) (*BuildTxResp, error)
	BuildLock(ctx context.Context, in *BuildLockReq, opts ...grpc.CallOption) (*BuildTxResp, error)
}

type defaultGovernanceService struct {
	cli zrpc.Client
}

func NewGovernanceService(cli zrpc.Client) GovernanceService {
	return &defaultGovernanceService{cli: cli}
}

func (d *defaultGovernanceService) GetProposals(ctx context.Context, in *GetProposalsReq, opts ...grpc.CallOption) (*GetProposalsResp, error) {
	client := governance.NewGovernanceServiceClient(d.cli.Conn())
	return client.GetProposals(ctx, in, opts...)
}

func (d *defaultGovernanceService) GetProposalDetail(ctx context.Context, in *GetProposalDetailReq, opts ...grpc.CallOption) (*GetProposalDetailResp, error) {
	client := governance.NewGovernanceServiceClient(d.cli.Conn())
	return client.GetProposalDetail(ctx, in, opts...)
}

func (d *defaultGovernanceService) GetVotes(ctx context.Context, in *GetVotesReq, opts ...grpc.CallOption) (*GetVotesResp, error) {
	client := governance.NewGovernanceServiceClient(d.cli.Conn())
	return client.GetVotes(ctx, in, opts...)
}

func (d *defaultGovernanceService) GetVeLock(ctx context.Context, in *GetVeLockReq, opts ...grpc.CallOption) (*GetVeLockResp, error) {
	client := governance.NewGovernanceServiceClient(d.cli.Conn())
	return client.GetVeLock(ctx, in, opts...)
}

func (d *defaultGovernanceService) BuildVote(ctx context.Context, in *BuildVoteReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := governance.NewGovernanceServiceClient(d.cli.Conn())
	return client.BuildVote(ctx, in, opts...)
}

func (d *defaultGovernanceService) BuildLock(ctx context.Context, in *BuildLockReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := governance.NewGovernanceServiceClient(d.cli.Conn())
	return client.BuildLock(ctx, in, opts...)
}
