// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthLoginReq struct {
	Address   string `json:"address"`
	Message   string `json:"message"`
	Signature string `json:"signature"`
}

type AuthNonceReq struct {
	Address string `json:"address"`
}

type AuthRefreshReq struct {
	RefreshToken string `json:"refreshToken"`
}

type BondsBuildClaimReq struct {
	BondId string `json:"bondId"`
}

type BondsBuildPurchaseReq struct {
	MarketAddress string `json:"marketAddress"`
	Amount        string `json:"amount"`
}

type BondsMarketDetailReq struct {
	MarketAddress string `path:"marketAddress"`
}

type BondsMarketsReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type DexCandlesReq struct {
	PairAddress string `path:"pairAddress"`
	Interval    string `form:"interval,default=1h"`
	From        int64  `form:"from,optional"`
	To          int64  `form:"to,optional"`
}

type DexFindRouteReq struct {
	TokenIn    string `form:"tokenIn"`
	TokenOut   string `form:"tokenOut"`
	AmountIn   string `form:"amountIn"`
	MaxHops    int    `form:"maxHops,default=3"`
	MaxResults int    `form:"maxResults,default=3"`
}

type DexPairDetailReq struct {
	PairAddress string `path:"pairAddress"`
}

type DexPairsReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Keyword  string `form:"keyword,optional"`
	SortBy   string `form:"sortBy,optional"`
}

type DexSwapBuildReq struct {
	TokenIn     string `json:"tokenIn"`
	TokenOut    string `json:"tokenOut"`
	AmountIn    string `json:"amountIn"`
	SlippageBps int    `json:"slippageBps,default=50"`
}

type DexTradesReq struct {
	PairAddress string `path:"pairAddress"`
	Page        int64  `form:"page,default=1"`
	PageSize    int64  `form:"pageSize,default=20"`
}

type FuturesBuildAdjustMarginReq struct {
	PositionId string `json:"positionId"`
	Amount     string `json:"amount"`
	IsAdd      bool   `json:"isAdd"`
}

type FuturesBuildCloseReq struct {
	PositionId string `json:"positionId"`
	Amount     string `json:"amount,optional"`
}

type FuturesBuildOpenReq struct {
	MarketAddress string `json:"marketAddress"`
	Side          string `json:"side"`
	Margin        string `json:"margin"`
	Leverage      string `json:"leverage"`
	LimitPrice    string `json:"limitPrice,optional"`
}

type FuturesFundingHistoryReq struct {
	MarketAddress string `path:"marketAddress"`
	Page          int64  `form:"page,default=1"`
	PageSize      int64  `form:"pageSize,default=20"`
}

type FuturesMarketDetailReq struct {
	MarketAddress string `path:"marketAddress"`
}

type FuturesMarketsReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type GovBuildLockReq struct {
	Amount   string `json:"amount"`
	Duration int64  `json:"duration"`
}

type GovBuildVoteReq struct {
	ProposalId string `json:"proposalId"`
	Support    int    `json:"support"`
	Reason     string `json:"reason,optional"`
}

type GovProposalDetailReq struct {
	ProposalId string `path:"proposalId"`
}

type GovProposalsReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Status   string `form:"status,optional"`
}

type GovVotesReq struct {
	ProposalId string `path:"proposalId"`
	Page       int64  `form:"page,default=1"`
	PageSize   int64  `form:"pageSize,default=20"`
}

type LendingBuildBorrowReq struct {
	AssetAddress string `json:"assetAddress"`
	Amount       string `json:"amount"`
}

type LendingBuildRepayReq struct {
	AssetAddress string `json:"assetAddress"`
	Amount       string `json:"amount"`
}

type LendingBuildSupplyReq struct {
	AssetAddress string `json:"assetAddress"`
	Amount       string `json:"amount"`
}

type LendingBuildWithdrawReq struct {
	AssetAddress string `json:"assetAddress"`
	Amount       string `json:"amount"`
}

type LendingLiquidationsReq struct {
	AssetAddress string `form:"assetAddress,optional"`
	UserAddress  string `form:"userAddress,optional"`
	Page         int64  `form:"page,default=1"`
	PageSize     int64  `form:"pageSize,default=20"`
}

type LendingMarketDetailReq struct {
	AssetAddress string `path:"assetAddress"`
}

type LendingMarketsReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Keyword  string `form:"keyword,optional"`
}

type OptionsVolSurfaceReq struct {
	Underlying string `path:"underlying"`
}

type PageReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type SystemReindexReq struct {
	Module    string `json:"module"`
	FromBlock int64  `json:"fromBlock"`
	ToBlock   int64  `json:"toBlock"`
}

type UserActivityReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Module   string `form:"module,optional"`
}

type UserSettingsReq struct {
	Nickname        string `json:"nickname,optional"`
	Language        string `json:"language,optional"`
	Currency        string `json:"currency,optional"`
	SlippageDefault int    `json:"slippageDefault,optional"`
}

type VaultBuildDepositReq struct {
	VaultAddress string `json:"vaultAddress"`
	Amount       string `json:"amount"`
}

type VaultBuildWithdrawReq struct {
	VaultAddress string `json:"vaultAddress"`
	Shares       string `json:"shares"`
}

type VaultDetailReq struct {
	VaultAddress string `path:"vaultAddress"`
}

type VaultListReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}
