// Code generated by goctl. DO NOT EDIT.
package futuresclient

import (
	"context"

	"github.com/reyfi/reyfi-backend/app/futures/rpc/futures"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMarketsReq          = futures.GetMarketsReq
	GetMarketsResp         = futures.GetMarketsResp
	FuturesMarketInfo      = futures.FuturesMarketInfo
	GetMarketDetailReq     = futures.GetMarketDetailReq
	GetMarketDetailResp    = futures.GetMarketDetailResp
	GetPositionsReq        = futures.GetPositionsReq
	GetPositionsResp       = futures.GetPositionsResp
	FuturesPositionInfo    = futures.FuturesPositionInfo
	GetFundingHistoryReq   = futures.GetFundingHistoryReq
	GetFundingHistoryResp  = futures.GetFundingHistoryResp
	FundingRateItem        = futures.FundingRateItem
	BuildOpenPositionReq   = futures.BuildOpenPositionReq
	BuildClosePositionReq  = futures.BuildClosePositionReq
	BuildAdjustMarginReq   = futures.BuildAdjustMarginReq
	BuildTxResp            = futures.BuildTxResp
)

type FuturesService interface {
	GetMarkets(ctx context.Context, in *GetMarketsReq, opts ...grpc.CallOption) (*GetMarketsResp, error)
	GetMarketDetail(ctx context.Context, in *GetMarketDetailReq, opts ...grpc.CallOption) (*GetMarketDetailResp, error)
	GetPositions(ctx context.Context, in *GetPositionsReq, opts ...grpc.CallOption) (*GetPositionsResp, error)
	GetFundingHistory(ctx context.Context, in *GetFundingHistoryReq, opts ...grpc.CallOption) (*GetFundingHistoryResp, error)
	BuildOpenPosition(ctx context.Context, in *BuildOpenPositionReq, opts ...grpc.CallOption) (*BuildTxResp, error)
	BuildClosePosition(ctx context.Context, in *BuildClosePositionReq, opts ...grpc.CallOption) (*BuildTxResp, error)
	BuildAdjustMargin(ctx context.Context, in *BuildAdjustMarginReq, opts ...grpc.CallOption) (*BuildTxResp, error)
}

type defaultFuturesService struct {
	cli zrpc.Client
}

func NewFuturesService(cli zrpc.Client) FuturesService {
	return &defaultFuturesService{cli: cli}
}

func (d *defaultFuturesService) GetMarkets(ctx context.Context, in *GetMarketsReq, opts ...grpc.CallOption) (*GetMarketsResp, error) {
	client := futures.NewFuturesServiceClient(d.cli.Conn())
	return client.GetMarkets(ctx, in, opts...)
}

func (d *defaultFuturesService) GetMarketDetail(ctx context.Context, in *GetMarketDetailReq, opts ...grpc.CallOption) (*GetMarketDetailResp, error) {
	client := futures.NewFuturesServiceClient(d.cli.Conn())
	return client.GetMarketDetail(ctx, in, opts...)
}

func (d *defaultFuturesService) GetPositions(ctx context.Context, in *GetPositionsReq, opts ...grpc.CallOption) (*GetPositionsResp, error) {
	client := futures.NewFuturesServiceClient(d.cli.Conn())
	return client.GetPositions(ctx, in, opts...)
}

func (d *defaultFuturesService) GetFundingHistory(ctx context.Context, in *GetFundingHistoryReq, opts ...grpc.CallOption) (*GetFundingHistoryResp, error) {
	client := futures.NewFuturesServiceClient(d.cli.Conn())
	return client.GetFundingHistory(ctx, in, opts...)
}

func (d *defaultFuturesService) BuildOpenPosition(ctx context.Context, in *BuildOpenPositionReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := futures.NewFuturesServiceClient(d.cli.Conn())
	return client.BuildOpenPosition(ctx, in, opts...)
}

func (d *defaultFuturesService) BuildClosePosition(ctx context.Context, in *BuildClosePositionReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := futures.NewFuturesServiceClient(d.cli.Conn())
	return client.BuildClosePosition(ctx, in, opts...)
}

func (d *defaultFuturesService) BuildAdjustMargin(ctx context.Context, in *BuildAdjustMarginReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := futures.NewFuturesServiceClient(d.cli.Conn())
	return client.BuildAdjustMargin(ctx, in, opts...)
}
