// Code generated by goctl. DO NOT EDIT.
package vaultclient

import (
	"context"

	"github.com/reyfi/reyfi-backend/app/vault/rpc/vault"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetVaultsReq       = vault.GetVaultsReq
	GetVaultsResp      = vault.GetVaultsResp
	VaultInfo          = vault.VaultInfo
	GetVaultDetailReq  = vault.GetVaultDetailReq
	GetVaultDetailResp = vault.GetVaultDetailResp
	GetPositionsReq    = vault.GetPositionsReq
	GetPositionsResp   = vault.GetPositionsResp
	VaultPositionInfo  = vault.VaultPositionInfo
	BuildDepositReq    = vault.BuildDepositReq
	BuildWithdrawReq   = vault.BuildWithdrawReq
	BuildTxResp        = vault.BuildTxResp
)

type VaultService interface {
	GetVaults(ctx context.Context, in *GetVaultsReq, opts ...grpc.CallOption) (*GetVaultsResp, error)
	GetVaultDetail(ctx context.Context, in *GetVaultDetailReq, opts ...grpc.CallOption) (*GetVaultDetailResp, error)
	GetPositions(ctx context.Context, in *GetPositionsReq, opts ...grpc.CallOption) (*GetPositionsResp, error)
	BuildDeposit(ctx context.Context, in *BuildDepositReq, opts ...grpc.CallOption) (*BuildTxResp, error)
	BuildWithdraw(ctx context.Context, in *BuildWithdrawReq, opts ...grpc.CallOption) (*BuildTxResp, error)
}

type defaultVaultService struct {
	cli zrpc.Client
}

func NewVaultService(cli zrpc.Client) VaultService {
	return &defaultVaultService{cli: cli}
}

func (d *defaultVaultService) GetVaults(ctx context.Context, in *GetVaultsReq, opts ...grpc.CallOption) (*GetVaultsResp, error) {
	client := vault.NewVaultServiceClient(d.cli.Conn())
	return client.GetVaults(ctx, in, opts...)
}

func (d *defaultVaultService) GetVaultDetail(ctx context.Context, in *GetVaultDetailReq, opts ...grpc.CallOption) (*GetVaultDetailResp, error) {
	client := vault.NewVaultServiceClient(d.cli.Conn())
	return client.GetVaultDetail(ctx, in, opts...)
}

func (d *defaultVaultService) GetPositions(ctx context.Context, in *GetPositionsReq, opts ...grpc.CallOption) (*GetPositionsResp, error) {
	client := vault.NewVaultServiceClient(d.cli.Conn())
	return client.GetPositions(ctx, in, opts...)
}

func (d *defaultVaultService) BuildDeposit(ctx context.Context, in *BuildDepositReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := vault.NewVaultServiceClient(d.cli.Conn())
	return client.BuildDeposit(ctx, in, opts...)
}

func (d *defaultVaultService) BuildWithdraw(ctx context.Context, in *BuildWithdrawReq, opts ...grpc.CallOption) (*BuildTxResp, error) {
	client := vault.NewVaultServiceClient(d.cli.Conn())
	return client.BuildWithdraw(ctx, in, opts...)
}
